Hi, I'm trying to run the notebook with my own model but I keep getting the following error when running the inference function:

ConnectionError: HTTPConnectionPool(host='ny1.ptopenlab.com', port=80): Max retries exceeded with url: /powerai-vision-ny/api/dlapis/00b984d5-489d-413e-9e47-c8824eba77ca (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000268B34A09B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

Does anybody have any idea about how i can solve it?
Thanks a lot
The code was updated so the download is from github instead of box, but the example output wasn't updated. Should grab a new one and also see if anything else is out of sync.
Mentions preview, Nimbix,...  Needs review. Also might just remove it as these are now preferred to be on the pattern page only.