ValueError                                Traceback (most recent call last)
<ipython-input-25-59a5369e1d73> in <module>()
      3 picks = []
      4 for i in range(5):
----> 5     rnd_index = np.random.randint(low=0,high=len(choices))
      6     picks.append(choices.pop(rnd_index))
      7 fig, axs = plt.subplots(2,5, figsize=(15, 6))

mtrand.pyx in mtrand.RandomState.randint()

ValueError: low >= high

Where is your 
`training_file = "./traffic-signs-data/train.p"`

`testing_file = "./traffic-signs-data/test.p"` ?

Please Upload these ? 